
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND FEATURE GIVEN SCENARIO TEXT THEN WHENfeatures : features feature\n| featurefeature : FEATURE TEXT scenariosscenarios : scenarios scenario\n| scenarioscenario : SCENARIO TEXT stepssteps : steps step\n| stepstep : GIVEN TEXT\n| WHEN TEXT\n| THEN TEXT\n| AND TEXT'
    
_lr_action_items = {'FEATURE':([0,1,2,4,6,7,9,11,12,17,18,19,20,21,],[3,3,-2,-1,-3,-5,-4,-6,-8,-7,-9,-10,-11,-12,]),'$end':([1,2,4,6,7,9,11,12,17,18,19,20,21,],[0,-2,-1,-3,-5,-4,-6,-8,-7,-9,-10,-11,-12,]),'TEXT':([3,8,13,14,15,16,],[5,10,18,19,20,21,]),'SCENARIO':([5,6,7,9,11,12,17,18,19,20,21,],[8,8,-5,-4,-6,-8,-7,-9,-10,-11,-12,]),'GIVEN':([10,11,12,17,18,19,20,21,],[13,13,-8,-7,-9,-10,-11,-12,]),'WHEN':([10,11,12,17,18,19,20,21,],[14,14,-8,-7,-9,-10,-11,-12,]),'THEN':([10,11,12,17,18,19,20,21,],[15,15,-8,-7,-9,-10,-11,-12,]),'AND':([10,11,12,17,18,19,20,21,],[16,16,-8,-7,-9,-10,-11,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'features':([0,],[1,]),'feature':([0,1,],[2,4,]),'scenarios':([5,],[6,]),'scenario':([5,6,],[7,9,]),'steps':([10,],[11,]),'step':([10,11,],[12,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> features","S'",1,None,None,None),
  ('features -> features feature','features',2,'p_features','gherkin_parser.py',10),
  ('features -> feature','features',1,'p_features','gherkin_parser.py',11),
  ('feature -> FEATURE TEXT scenarios','feature',3,'p_feature','gherkin_parser.py',18),
  ('scenarios -> scenarios scenario','scenarios',2,'p_scenarios','gherkin_parser.py',28),
  ('scenarios -> scenario','scenarios',1,'p_scenarios','gherkin_parser.py',29),
  ('scenario -> SCENARIO TEXT steps','scenario',3,'p_scenario','gherkin_parser.py',36),
  ('steps -> steps step','steps',2,'p_steps','gherkin_parser.py',43),
  ('steps -> step','steps',1,'p_steps','gherkin_parser.py',44),
  ('step -> GIVEN TEXT','step',2,'p_step','gherkin_parser.py',51),
  ('step -> WHEN TEXT','step',2,'p_step','gherkin_parser.py',52),
  ('step -> THEN TEXT','step',2,'p_step','gherkin_parser.py',53),
  ('step -> AND TEXT','step',2,'p_step','gherkin_parser.py',54),
]
